name: Generate Profile Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: generate-profile-metrics
  cancel-in-progress: true

jobs:
  generate-profile-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate profile overview
        uses: lowlighter/metrics@latest
        with:
          filename: assets/profile-metrics/github-metrics.svg
          base: header, repositories
          plugin_lines: yes
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate PageSpeed report
        uses: lowlighter/metrics@latest
        with:
          filename: assets/profile-metrics/metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://bugwz.com
          plugin_pagespeed_detailed: false
          plugin_pagespeed_screenshot: false
          plugin_pagespeed_pwa: false

      - name: Generate starred topics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/profile-metrics/metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics_sort: stars
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Generate star lists
        uses: lowlighter/metrics@latest
        with:
          filename: assets/profile-metrics/metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8

      - name: Generate website screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: assets/profile-metrics/metrics.plugin.screenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: https://bugwz.com
          plugin_screenshot_url: https://bugwz.com
          plugin_screenshot_selector: "#body-wrap"
          plugin_screenshot_mode: image
          plugin_screenshot_viewport: '{"width": 1280,"height": 600}'
