name: Generate Profile Metrics

on:
  schedule:
    - cron: "53 22 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/profile-metrics.yml

permissions:
  contents: write

concurrency:
  group: workflow-profile-metrics
  cancel-in-progress: true

jobs:
  generate-profile-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate profile overview
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          output_action: none
          base: header, repositories
          plugin_lines: yes
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate starred topics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          output_action: none
          token: NOT_NEEDED
          base: ""
          plugin_topics_sort: stars
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Generate star lists
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          output_action: none
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8

      - name: Generate website screenshot
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.screenshot.svg
          output_action: none
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: https://bugwz.com
          plugin_screenshot_url: https://bugwz.com
          plugin_screenshot_selector: "#body-wrap"
          plugin_screenshot_mode: image
          plugin_screenshot_viewport: '{"width": 1280,"height": 600}'

      - name: Stage profile metrics
        run: |
          mkdir -p dist
          cp /metrics_renders/*.svg dist/

      - name: Publish profile metrics
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: workflow-profile-metrics
          publish_dir: ./dist
          force_orphan: true
