name: Generate README Stats

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/readme-stats.yml
  schedule:
    - cron: "37 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: workflow-readme-stats
  cancel-in-progress: true

jobs:
  generate-readme-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2.0.2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Publish stats card
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: workflow-readme-stats
          publish_dir: ./dist
          force_orphan: true
